# Week 6-10 영어 텍스트 군집 분석 Lab

1. smartthings_e_review_result.csv 파일을 열어서 review_df에 저장하시오.

In [1]:
import os
import pandas as pd

os.chdir(r'C:\Users\Administrator\Downloads\6주차_11일차,12일차_자연어처리\Week6 자연어처리 Data')
review_df=pd.read_csv("smartthings_e_review_result.csv")

review_df

date  star  like  \
0      September 19, 2021     1  15.0   
1      September 17, 2021     1  12.0   
2      September 17, 2021     2  11.0   
3      September 15, 2021     2  15.0   
4      September 11, 2021     1   8.0   
...                   ...   ...   ...   
10955   November 16, 2019     1   NaN   
10956   December 12, 2020     3   NaN   
10957   December 14, 2019     1   NaN   
10958    January 17, 2019     1   NaN   
10959     January 8, 2020     4   NaN   

                                                 comment  \
0      Really unbelievable you can't even turn on a S...   
1      This app is so bad. It continually and randoml...   
2      I have this app on Android and iOS. It will no...   
3      Watch app does not sync current state status f...   
4      Unable to add my hue lights, every function co...   
...                                                  ...   
10955  Wont connect to my Samsung tv. Using samsung p...   
10956  This is good but have one issue with 4D-pad wh...   
10957  App crashes and stops. Removed, reinstall, try...   
10958  since this smart things came in they took the ...   
10959  It is good, you can do a lot, wish if they can...   

                                               comment_n  
0      ['really', 'unbelievable', 'even', 'turn', 'sa...  
1      ['app', 'bad', 'continually', 'randomly', 'tra...  
2      ['app', 'android', 'io', 'allow', 'add', 'phot...  
3      ['watch', 'app', 'sync', 'current', 'state', '...  
4      ['unable', 'add', 'hue', 'light', 'every', 'fu...  
...                                                  ...  
10955  ['wont', 'connect', 'samsung', 'tv', 'using', ...  
10956  ['good', 'one', 'issue', 'pad', 'app', 'go', '...  
10957  ['app', 'crash', 'stop', 'removed', 'reinstall...  
10958  ['since', 'smart', 'thing', 'came', 'took', 'q...  
10959  ['good', 'lot', 'wish', 'add', 'flexibility', ...  

[10960 rows x 5 columns]

In [2]:
review_df['comment_n_str']=review_df['comment_n'].apply(lambda x: " ".join(eval(x)))
review_df

date  star  like  \
0      September 19, 2021     1  15.0   
1      September 17, 2021     1  12.0   
2      September 17, 2021     2  11.0   
3      September 15, 2021     2  15.0   
4      September 11, 2021     1   8.0   
...                   ...   ...   ...   
10955   November 16, 2019     1   NaN   
10956   December 12, 2020     3   NaN   
10957   December 14, 2019     1   NaN   
10958    January 17, 2019     1   NaN   
10959     January 8, 2020     4   NaN   

                                                 comment  \
0      Really unbelievable you can't even turn on a S...   
1      This app is so bad. It continually and randoml...   
2      I have this app on Android and iOS. It will no...   
3      Watch app does not sync current state status f...   
4      Unable to add my hue lights, every function co...   
...                                                  ...   
10955  Wont connect to my Samsung tv. Using samsung p...   
10956  This is good but have one issue with 4D-pad wh...   
10957  App crashes and stops. Removed, reinstall, try...   
10958  since this smart things came in they took the ...   
10959  It is good, you can do a lot, wish if they can...   

                                               comment_n  \
0      ['really', 'unbelievable', 'even', 'turn', 'sa...   
1      ['app', 'bad', 'continually', 'randomly', 'tra...   
2      ['app', 'android', 'io', 'allow', 'add', 'phot...   
3      ['watch', 'app', 'sync', 'current', 'state', '...   
4      ['unable', 'add', 'hue', 'light', 'every', 'fu...   
...                                                  ...   
10955  ['wont', 'connect', 'samsung', 'tv', 'using', ...   
10956  ['good', 'one', 'issue', 'pad', 'app', 'go', '...   
10957  ['app', 'crash', 'stop', 'removed', 'reinstall...   
10958  ['since', 'smart', 'thing', 'came', 'took', 'q...   
10959  ['good', 'lot', 'wish', 'add', 'flexibility', ...   

                                           comment_n_str  
0      really unbelievable even turn samsung televisi...  
1      app bad continually randomly transfer audio ou...  
2      app android io allow add photo gallery frame t...  
3      watch app sync current state status favorite c...  
4      unable add hue light every function come fail ...  
...                                                  ...  
10955  wont connect samsung tv using samsung phone fr...  
10956  good one issue pad app go inactive pad working...  
10957  app crash stop removed reinstall try sign netw...  
10958  since smart thing came took quick connect away...  
10959  good lot wish add flexibility automation advan...  

[10960 rows x 6 columns]

2. comment_n 컬럼값을 리스트로 변환하고 다시 하나의 문자열로 만들어서 comment_n_str 컬럼을 추가하시오.

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidfv = TfidfVectorizer(stop_words='english',ngram_range=(1,2), min_df=0.01,max_df=0.95)
feature_vect=tfidfv.fit_transform(review_df['comment_n_str'])

In [4]:
feature_vect

<10960x327 sparse matrix of type '<class 'numpy.float64'>'
	with 114719 stored elements in Compressed Sparse Row format>

3. commnet_n_str 컬럼을 사용하여 TfidfVectorizer를 이용하여 DTM를 생성하시오.

4. K=10으로 해서 K-means 군집화 방법을 이용하여 군집을 생성하시오.

In [6]:
from sklearn.cluster import KMeans
km_cluster = KMeans(n_clusters=10, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
cluster_centers = km_cluster.cluster_centers_

In [7]:
print(cluster_label)
print(cluster_centers)

[1 9 7 ... 1 6 1]
[[0.00036655 0.02199094 0.0035518  ... 0.00299668 0.00724214 0.00452505]
 [0.00518779 0.01094907 0.00620323 ... 0.00326791 0.0051393  0.00891199]
 [0.00374512 0.02700723 0.00340098 ... 0.00327878 0.00436859 0.00953074]
 ...
 [0.00651682 0.01466034 0.00366649 ... 0.0032183  0.00281964 0.01080869]
 [0.00459307 0.01195164 0.0060169  ... 0.01228413 0.00716668 0.01080284]
 [0.00756387 0.02267678 0.00221054 ... 0.00183143 0.00041767 0.00169908]]


In [8]:
cluster_centers.shape

(10, 327)

In [9]:
review_df['cluster_label'] = cluster_label
review_df.head()

date  star  like  \
0  September 19, 2021     1  15.0   
1  September 17, 2021     1  12.0   
2  September 17, 2021     2  11.0   
3  September 15, 2021     2  15.0   
4  September 11, 2021     1   8.0   

                                             comment  \
0  Really unbelievable you can't even turn on a S...   
1  This app is so bad. It continually and randoml...   
2  I have this app on Android and iOS. It will no...   
3  Watch app does not sync current state status f...   
4  Unable to add my hue lights, every function co...   

                                           comment_n  \
0  ['really', 'unbelievable', 'even', 'turn', 'sa...   
1  ['app', 'bad', 'continually', 'randomly', 'tra...   
2  ['app', 'android', 'io', 'allow', 'add', 'phot...   
3  ['watch', 'app', 'sync', 'current', 'state', '...   
4  ['unable', 'add', 'hue', 'light', 'every', 'fu...   

                                       comment_n_str  cluster_label  
0  really unbelievable even turn samsung televisi...              1  
1  app bad continually randomly transfer audio ou...              9  
2  app android io allow add photo gallery frame t...              7  
3  watch app sync current state status favorite c...              1  
4  unable add hue light every function come fail ...              1

5. 생성된 군집 레이블을 'cluster_label' 컬럼으로 review_df에 추가하시오.

In [10]:
review_df[review_df['cluster_label']==0].sort_values(by='comment_n_str')

date  star  like  \
10332      June 11, 2019     1   NaN   
9901   November 12, 2019     1   NaN   
1358       July 14, 2021     3   NaN   
2295       June 19, 2021     1   NaN   
8726      April 21, 2019     1   NaN   
...                  ...   ...   ...   
5609       July 18, 2020     4   NaN   
10515  February 10, 2019     4   NaN   
9727   December 13, 2020     4   NaN   
5575   November 17, 2020     1   NaN   
4811    February 1, 2019     1   1.0   

                                                 comment  \
10332  I am not able to connect to my TV , i have sam...   
9901   not able to connect with tv (ua32n4305arxxl), ...   
1358   Not able to control the television consistentl...   
2295   Not able to get my tv to connect anymore and c...   
8726   I am not able to use it any more for couple of...   
...                                                  ...   
5609   I would love it if you could get it to connect...   
10515  it would be nice if more brands could connect ...   
9727   I would prefer that it automatically connect s...   
5575   Yesterday, my the app prompted to put in the P...   
4811   ZERO STARS terrible, when I first downloaded t...   

                                               comment_n  \
10332  ['able', 'connect', 'tv', 'samsung', 'smart', ...   
9901   ['able', 'connect', 'tv', 'ua', 'n', 'arxxl', ...   
1358   ['able', 'control', 'television', 'consistentl...   
2295   ['able', 'get', 'tv', 'connect', 'anymore', 'c...   
8726   ['able', 'use', 'couple', 'day', 'easy', 'conn...   
...                                                  ...   
5609   ['would', 'love', 'could', 'get', 'connect', '...   
10515  ['would', 'nice', 'brand', 'could', 'connect',...   
9727   ['would', 'prefer', 'automatically', 'connect'...   
5575   ['yesterday', 'app', 'prompted', 'put', 'pin',...   
4811   ['zero', 'star', 'terrible', 'first', 'downloa...   

                                           comment_n_str  cluster_label  
10332  able connect tv samsung smart tv tried many da...              0  
9901   able connect tv ua n arxxl try lot time even a...              0  
1358   able control television consistently many time...              0  
2295            able get tv connect anymore connect echo              0  
8726   able use couple day easy connect seem find tv ...              0  
...                                                  ...            ...  
5609   would love could get connect tv fast trying tu...              0  
10515  would nice brand could connect app samsung bra...              0  
9727   would prefer automatically connect sound phone...              0  
5575   yesterday app prompted put pin tv say incorrec...              0  
4811   zero star terrible first downloaded app sort w...              0  

[711 rows x 7 columns]

6. 군집 0, 1, 9에 속한 레코드들을 출력하시오.

In [11]:
review_df[review_df['cluster_label']==1].sort_values(by='comment_n_str')

date  star  like  \
9296    November 26, 2020     2   NaN   
4869    February 17, 2019     1   8.0   
850         July 23, 2021     1   1.0   
4629     November 9, 2020     1   NaN   
6223        March 6, 2021     1   2.0   
...                   ...   ...   ...   
3754         May 16, 2020     1   1.0   
9035     October 30, 2020     1   NaN   
85     September 10, 2021     1   1.0   
10488   November 10, 2020     4   NaN   
3034        June 24, 2021     2   NaN   

                                                 comment  \
9296   The ability to add new Smart Apps has suddenly...   
4869   The ability to edit scenes/automation is broke...   
850    It's abit useless really. Constantly saying li...   
4629   I haven't been able to access my TV for weeks....   
6223   I haven't been able to connect my garage or Go...   
...                                                  ...   
3754   Zero stars, this update has been the WORST. I ...   
9035   ZERO STARS! Updating it crashed my phone so ha...   
85     zFold 3 not supported/issues. Works, but smart...   
10488  Сделайте реакцию на нажатие кнопки. А то нажим...   
3034   맨날 연결 끊기고 업데이트하고.. 뭐냐.. 3류 회사마냥. Can't underst...   

                                               comment_n  \
9296   ['ability', 'add', 'new', 'smart', 'apps', 'su...   
4869   ['ability', 'edit', 'scene', 'automation', 'br...   
850    ['abit', 'useless', 'really', 'constantly', 's...   
4629   ['able', 'access', 'tv', 'week', 'keep', 'tell...   
6223   ['able', 'connect', 'garage', 'google', 'nest'...   
...                                                  ...   
3754   ['zero', 'star', 'update', 'worst', 'return', ...   
9035   ['zero', 'star', 'updating', 'crashed', 'phone...   
85     ['zfold', 'supported', 'issue', 'work', 'smart...   
10488  ['сделайте', 'реакцию', 'на', 'нажатие', 'кноп...   
3034   ['맨날', '연결', '끊기고', '업데이트하고', '뭐냐', '류', '회사마냥...   

                                           comment_n_str  cluster_label  
9296   ability add new smart apps suddenly vanished c...              1  
4869   ability edit scene automation broken way edit ...              1  
850    abit useless really constantly saying light ri...              1  
4629   able access tv week keep telling trouble conne...              1  
6223   able connect garage google nest last update fr...              1  
...                                                  ...            ...  
3754   zero star update worst return phone waste time...              1  
9035   zero star updating crashed phone hard get blue...              1  
85     zfold supported issue work smarttag connecting...              1  
10488  сделайте реакцию на нажатие кнопки а то нажима...              1  
3034   맨날 연결 끊기고 업데이트하고 뭐냐 류 회사마냥 understand ask bos ...              1  

[3667 rows x 7 columns]

7. 각 군집별로 핵심 단어를 10개씩 추출하시오.

In [12]:
review_df[review_df['cluster_label']==9].sort_values(by='comment_n_str')

date  star  like  \
5780      March 5, 2019     4   NaN   
1663      July 13, 2021     5   NaN   
252   September 1, 2021     5   NaN   
7936  February 20, 2021     5   1.0   
429     August 10, 2021     5   2.0   
...                 ...   ...   ...   
2091       May 22, 2021     4   1.0   
4983  November 20, 2020     3   NaN   
3911  December 23, 2019     1  18.0   
3062   December 1, 2020     5   NaN   
5165   January 28, 2020     1   NaN   

                                                comment  \
5780  the ability to change the audio output of blue...   
1663  Ability to switch between audio output devices...   
252   Being able to switch from Bluetooth to speaker...   
7936  Absolutely fantastic, especially the feature t...   
429   I absolutely love the ability to easily switch...   
...                                                 ...   
2091  Would like to have surround sound option when ...   
4983  It would be nice to be able to lock which devi...   
3911  It's been a year and a half with bluetooth no ...   
3062  I have yet to try all of the features. I predo...   
5165  Zero rating. This app wrecked my hearing aid a...   

                                              comment_n  \
5780  ['ability', 'change', 'audio', 'output', 'blue...   
1663  ['ability', 'switch', 'audio', 'output', 'devi...   
252   ['able', 'switch', 'bluetooth', 'speaker', 'au...   
7936  ['absolutely', 'fantastic', 'especially', 'fea...   
429   ['absolutely', 'love', 'ability', 'easily', 's...   
...                                                 ...   
2091  ['would', 'like', 'surround', 'sound', 'option...   
4983  ['would', 'nice', 'able', 'lock', 'device', 'u...   
3911  ['year', 'half', 'bluetooth', 'longer', 'worki...   
3062  ['yet', 'try', 'feature', 'predominantly', 'us...   
5165  ['zero', 'rating', 'app', 'wrecked', 'hearing'...   

                                          comment_n_str  cluster_label  
5780  ability change audio output bluetooth music co...              9  
1663     ability switch audio output device really nice              9  
252   able switch bluetooth speaker audio without di...              9  
7936  absolutely fantastic especially feature perman...              9  
429   absolutely love ability easily switch audio ou...              9  
...                                                 ...            ...  
2091  would like surround sound option connected blu...              9  
4983  would nice able lock device using vehicle blue...              9  
3911  year half bluetooth longer working hyundai med...              9  
3062  yet try feature predominantly use audio output...              9  
5165  zero rating app wrecked hearing aid app contro...              9  

[581 rows x 7 columns]

8. PCA를 이용해서 이차원으로 차원 축소를 하고 이 결과를 review_df에 'ftr1','ftr2' 컬럼으로 추가하시오.

In [13]:
cluster_centers = km_cluster.cluster_centers_
print('cluster_centers shape :',cluster_centers.shape)
print(cluster_centers)

cluster_centers shape : (10, 327)
[[0.00036655 0.02199094 0.0035518  ... 0.00299668 0.00724214 0.00452505]
 [0.00518779 0.01094907 0.00620323 ... 0.00326791 0.0051393  0.00891199]
 [0.00374512 0.02700723 0.00340098 ... 0.00327878 0.00436859 0.00953074]
 ...
 [0.00651682 0.01466034 0.00366649 ... 0.0032183  0.00281964 0.01080869]
 [0.00459307 0.01195164 0.0060169  ... 0.01228413 0.00716668 0.01080284]
 [0.00756387 0.02267678 0.00221054 ... 0.00183143 0.00041767 0.00169908]]


9. 군집화 결과를 가시화하시오.

In [14]:
def get_cluster_details(cluster_model, cluster_data, feature_names, clusters_num, top_n_features=10):
    cluster_details = {}
    
    # cluster_centers array 의 값이 큰 순으로 정렬된 index 값을 반환
    # 군집 중심점(centroid)별 할당된 word 피처들의 거리값이 큰 순으로 값을 구하기 위함.  
    centroid_feature_ordered_ind = cluster_model.cluster_centers_.argsort()[:,::-1]
    
    #개별 군집별로 iteration하면서 핵심단어, 그 단어의 중심 위치 상대값 입력
    for cluster_num in range(clusters_num):
        # 개별 군집별 정보를 담을 데이터 초기화. 
        cluster_details[cluster_num] = {}
        cluster_details[cluster_num]['cluster'] = cluster_num
        
        # cluster_centers_.argsort()[:,::-1] 로 구한 index 를 이용하여 top n 피처 단어를 구함. 
        top_feature_indexes = centroid_feature_ordered_ind[cluster_num, :top_n_features]
        top_features = [ feature_names[ind] for ind in top_feature_indexes ]
        
        # top_feature_indexes를 이용해 해당 피처 단어의 중심 위치 상댓값 구함 
        top_feature_values = cluster_model.cluster_centers_[cluster_num, top_feature_indexes].tolist()
        
        # cluster_details 딕셔너리 객체에 개별 군집별 핵심 단어와 중심위치 상대값 입력
        cluster_details[cluster_num]['top_features'] = top_features
        cluster_details[cluster_num]['top_features_value'] = top_feature_values
        
    return cluster_details

10. DBSCAN 방법을 이용해서 군집화를 수행하시오. 단 eps은 0.6, min_samples 는 7로 하시오.

11. 군집화 결과를 review_df의 'dbscan_cluster' 컬럼으로 추가하시오. 또 각 군집에 몇 개의 레코드들이 할당되었는지 확인하시오.

12. 군집화 결과를 가시화하시오.

13. 군집 3에 배정된 레코드들을 출력하시오.

14.  DBSCAN 방법을 이용해서 군집화를 수행하시오. 단 eps은 0.5, min_samples 는 7로 하시오. 군집의 갯수가 몇 개 생성되었는지, 각 군집에 몇 개의 레코드가 할당되었는지 확인하시오.